apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: sample-function-app
  spec:
    replicas: 3
    selector:
      matchLabels:
        app.kubernetes.io/name: sample-function-app
    template:
      metadata:
        labels:
          app.kubernetes.io/name: sample-function-app
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: azure-key-vault-app-secrets-1
          - configMapRef:
              name: sample-function-app-config
          image: myregistry.azurecr.io/samples/dotnet:latest
          name: sample-function-app
          ports:
          - containerPort: 8080
            name: http
          volumeMounts:
          - mountPath: /mnt/secrets-app-secrets-1
            name: azure-key-vault-app-secrets-1
            readOnly: true
        - image: mcr.microsoft.com/dotnet/monitor:6.0.0
          name: dotnet-monitor
        volumes:
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-key-vault-app-secrets-1
          name: azure-key-vault-app-secrets-1
- apiVersion: v1
  data:
    EventHub__ConsumerGroup: something-consumer-group
    EventHub__Name: something
    EventHub__SubscriptionName: sbs-something-dev-01
    ServiceBus__TopicName: sbt-something-dev-01
  kind: ConfigMap
  metadata:
    name: sample-function-app-config
- apiVersion: secrets-store.csi.x-k8s.io/v1
  kind: SecretProviderClass
  metadata:
    name: azure-key-vault-app-secrets-1
  spec:
    parameters:
      keyvaultName: app-secrets-1
      objects: |
        array:
        - |
          objectName: event-hub-connection-string
          objectAlias: EventHub__ConnectionString
          objectType: secret
        - |
          objectName: service-bus-connection-string
          objectAlias: ServiceBus__ConnectionString
          objectType: secret
      tenantId: ""
      usePodIdentity: "false"
      useVMManagedIdentity: "true"
      userAssignedIdentityID: ""
    provider: azure
- apiVersion: v1
  kind: Service
  metadata:
    name: sample-function-app
  spec:
    ports:
    - port: 80
      targetPort: http
    selector:
      app.kubernetes.io/name: sample-function-app
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    name: sample-function-app
  spec:
    ingressClassName: ingress-nginx
    rules:
    - host: www.example.com
    - host: www2.example.com
    tls:
    - hosts:
      - www.example.com
      - www2.example.com
      secretName: www-example-com-tls
kind: List
